### ISSUE TITLE
Android S3 Jelly Bean 4.1.2

### ISSUE THREAD

**Issue by Onslot** [triceam/app-UI#49]
@triceam I was wondering if you could tell me what I am doing different, i am using your Fresh Food Finder as an example, when I loaded up the app from google market the animation works smoothly my test is just pressing the About button then back. My issue is when i try to recreate the app the animation header "Welcome" when i click about the back button and the title sort of flinches left to right, when i click the back button it places the welcome position to the right and chopped off part of m and e.
![screenshot_2013-08-01-13-27-59](https://f.cloud.github.com/assets/4615300/896622/4dd516fe-fae3-11e2-85fa-ed14f8a777f9.png)

**Comment by triceam** [comment]
Unforutnately, that's an issue with css translate3d transform on some Android devices. whenever the web view on android is based on Blink/Chrome instead of the legacy webkit version, this will go away.  Until then it's an issue.  This is a known issue in Android web views, and it only happens on some devices.  Unfortunately there is no reliable way to detect/workaround.  It's odd that it works on the version from the Google Play store, but not the local build.  The only difference would be b/c the one on the Google Play store was compiled with an older version of the Android SDK.  I usually chalk this up to another Android fragementation issue - sorry I don't have a better answer.

**Comment by triceam** [comment]
When you touch the screen again, does it re-render and fix itself?  I've seen this happen where it shows incorrectly, then as soon as you touch the screen again, it corrects itself.   Again, a weird Android issue.

**Comment by Onslot** [comment]
Hi Andrew,

Thanks for your quick reply! No when i just touch the screen it does not go back but if i scroll then it will return to the normal position. 

Thanks again!

**Comment by roopchand** [comment]
facing same problem in HTC android device ,when i scroll then it will return to the normal position.
Please suggest some solution.
Thanks
